server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphqldb?useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

graphql:
  servlet.mapping: /graphql
